language: python
python:
    - 2.7
    - 3.5

env:
    - PEEWEE_TEST_BACKEND=sqlite

install:
    - pip install tox codecov

before_script:
    - sh -c "python setup.py install"

script:
    - python runtests.py -e sqlite

notifications:
    email: false
